spring:
  application:
    name: conductor-boot-wrapper-secure
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: validate
  flyway:
    validate-on-migrate: true
    baseline-on-migrate: true
    locations:
    - classpath:db/migration

MYSQL_DATABASE: conductor
MYSQL_USER: conductor
MYSQL_PASSWORD: Conductor@1234
MYSQL_DATABASE_HOST: localhost
MYSQL_DATABASE_PORT: 3306
AAASERVER_HOST: localhost
AAASERVER_PORT: 1024
AAA_CLIENT_ID: CONDUCTOR_USER_APP
AAA_CLIENT_SECRET: password
ELASTICSEARCH_HOST: localhost
ELASTICSEARCH_PORT: 9200