spring:
  profiles:
    active: 
     - default
     - database-default
     - logbook
     - mariadb-embedded
     - conductor
     - ports
     - zuul
     - security
  application:
    name: conductor-boot-wrapper-secure

server:
  port: 8080
  use-forward-headers: true

check-user-scopes: true
awaitTermination: 3000