oauth:
  security: EXTERNAL
 
AAA_CLIENT_ID: CONDUCTOR_USER_APP
AAA_CLIENT_SECRET: password
 
security:
  oauth2:
    resource:
      token-info-uri: http://${AAASERVER_HOST}:${AAASERVER_PORT}/oauth/check_token
    client:
      client-id: ${AAA_CLIENT_ID}
      client-secret: ${AAA_CLIENT_SECRET}