logbook:
  filter:
    enabled: true
  write:
    level: info
  format:
    style: splunk
  exclude: [/actuator/**, /v3/api-docs/**, /swagger-ui/**, /index.html, /images/**, /swagger-ui.js, /lib/**, /css/**, /api/swagger.json, /api/health]
  strategy: body-only-if-status-at-least
  minimum-status: 400
  obfuscate:
    headers:
      - Authorization
    parameters:
      - access_token
      - password